INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('101', 'Rape', '1999-05-12', 'PS1');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('102', 'Fraud', '2000-07-21', 'PS2');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('103', 'Hoarding', '2000-09-07', 'PS3');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('104', 'Money Laundering', '2001-01-24', 'PS2');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('105', 'Fraud', '2001-07-06', 'PS2');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('106', 'Rape', '2003-08-08', 'PS1');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('107', 'B&E', '1998-10-10', 'PS4');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('108', 'Chain Snatching', '1961-02-12', 'PS4');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('109', 'Assault', '2006-03-14', 'PS3');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('110', 'Murder', '2001-07-15', 'PS1');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('201', 'B&E', '2007-06-18', 'PS2');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('202', 'Rape', '1971-05-17', 'PS3');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('203', 'Blackmail', '1966-07-17', 'PS1');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('204', 'Fraud', '1993-10-23', 'PS3');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('205', 'Blackmail', '1981-05-25', 'PS2');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('206', 'Assault', '1977-06-27', 'PS4');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('207', 'Hoarding', '1999-12-04', 'PS1');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('208', 'Money Laundering', '2000-05-16', 'PS4');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('209', 'B&E', '1994-05-05', 'PS2');
INSERT INTO `communityindex`.`crime` (`Crime_ID`, `Criminal_Activity`, `Activity_Date`, `Police_Station_Jurisdiction_ID`) VALUES ('210', 'Murder', '1996-11-02', 'PS3');
