INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('101', 'Res4BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('102', 'Res4BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('103', 'Res4BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('104', 'Res4BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('105', 'Res4BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('106', 'Res4BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('107', 'Res4BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('108', 'Res4BHK', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('109', 'Res4BHK', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('110', 'Res4BHK', 'Nehrunagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('111', 'Res4BHK', 'University');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('112', 'Res4BHK', 'C.G. Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('113', 'Res4BHK', 'C.G.Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('114', 'Res4BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('115', 'Res4BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('116', 'Res4BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('117', 'Res4BHK', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('118', 'Res4BHK', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('119', 'Res4BHK', 'S.G. Highway');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('120', 'Res4BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('201', 'Res3BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('202', 'Res3BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('203', 'Res3BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('204', 'Res3BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('205', 'Res3BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('206', 'Res3BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('207', 'Res3BHK', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('208', 'Res3BHK', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('209', 'Res3BHK', 'Nehrunagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('210', 'Res3BHK', 'University');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('211', 'Res3BHK', 'C.G. Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('212', 'Res3BHK', 'C.G.Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('213', 'Res3BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('214', 'Res3BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('215', 'Res3BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('216', 'Res3BHK', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('217', 'Res3BHK', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('218', 'Res3BHK', 'S.G. Highway');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('219', 'Res3BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('220', 'Res3BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('221', 'Res3BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('222', 'Res3BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('223', 'Res3BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('224', 'Res3BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('225', 'Res3BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('226', 'Res3BHK', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('227', 'Res3BHK', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('228', 'Res3BHK', 'Nehrunagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('229', 'Res3BHK', 'University');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('230', 'Res3BHK', 'C.G. Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('231', 'Res3BHK', 'C.G.Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('232', 'Res3BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('233', 'Res3BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('301', 'Res2BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('302', 'Res2BHK', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('303', 'Res2BHK', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('304', 'Res2BHK', 'S.G. Highway');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('305', 'Res2BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('306', 'Res2BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('307', 'Res2BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('308', 'Res2BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('309', 'Res2BHK', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('310', 'Res2BHK', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('311', 'Res2BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('312', 'Res2BHK', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('313', 'Res2BHK', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('314', 'Res2BHK', 'Nehrunagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('315', 'Res2BHK', 'University');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('316', 'Res2BHK', 'C.G. Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('317', 'Res2BHK', 'C.G.Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('318', 'Res2BHK', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('319', 'Res2BHK', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('320', 'Res2BHK', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('401', 'Bunglows', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('402', 'Bunglows', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('403', 'Bunglows', 'S.G. Highway');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('404', 'Bunglows', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('405', 'Bunglows', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('406', 'Bunglows', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('407', 'Bunglows', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('408', 'Bunglows', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('409', 'Bunglows', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('410', 'Bunglows', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('411', 'Bunglows', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('412', 'Bunglows', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('413', 'Bunglows', 'Nehrunagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('414', 'Bunglows', 'University');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('415', 'Bunglows', 'C.G. Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('416', 'Bunglows', 'C.G.Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('417', 'Bunglows', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('418', 'Bunglows', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('419', 'Bunglows', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('420', 'Bunglows', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('501', 'Tenaments', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('502', 'Tenaments', 'S.G. Highway');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('503', 'Tenaments', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('504', 'Tenaments', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('505', 'Tenaments', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('506', 'Tenaments', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('507', 'Tenaments', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('508', 'Tenaments', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('509', 'Tenaments', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('510', 'Tenaments', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('511', 'Tenaments', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('512', 'Tenaments', 'Nehrunagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('513', 'Tenaments', 'University');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('514', 'Tenaments', 'C.G. Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('515', 'Tenaments', 'C.G.Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('516', 'Tenaments', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('517', 'Tenaments', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('518', 'Tenaments', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('519', 'Tenaments', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('520', 'Tenaments', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('601', 'Commercial', 'S.G. Highway');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('602', 'Commercial', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('603', 'Commercial', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('604', 'Commercial', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('605', 'Commercial', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('606', 'Commercial', 'Navrangpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('607', 'Commercial', 'Naranpura');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('608', 'Commercial', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('609', 'Commercial', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('610', 'Commercial', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('611', 'Commercial', 'Nehrunagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('612', 'Commercial', 'University');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('613', 'Commercial', 'C.G. Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('614', 'Commercial', 'C.G.Road');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('615', 'Commercial', 'Paldi');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('616', 'Commercial', 'Satellite');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('617', 'Commercial', 'Vasna');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('618', 'Commercial', 'Prahladnagar');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('619', 'Commercial', 'Ghatlodia');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('620', 'Commercial', 'S.G. Highway');
INSERT INTO `communityindex`.`property` (`Property_ID`, `Property_Type`, `Address`) VALUES ('621', 'Commercial', 'Navrangpura');
